site_name: TeamStation AI
site_url: https://teamstation-ai.github.io/CTO-playbook/
repo_name: TeamStation-AI/CTO-playbook
repo_url: https://github.com/TeamStation-AI/CTO-playbook
site_description: Build predictable, auditable nearshore engineering extensions with TeamStation AI™ under one SLA. Cognitive AI evaluations, onboarding, devices/MDM, EOR, and performance (BARS).

docs_dir: docs
strict: true

theme:
  name: material
  language: en
  favicon: "assets/TS new logo concept 2024.png"
  custom_dir: overrides
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - assets/custom.css
  - assets/custom.v2.css
  - assets/site.css

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.magiclink

plugins:
  - search
  - sitemap
  - seo:
      site_description: "Build predictable, auditable nearshore engineering extensions with TeamStation AI™ under one SLA. Cognitive AI evaluations, onboarding, devices/MDM, EOR, and performance (BARS)."

nav:
  - CTO Playbook: index.md
  - Strategy:
      - Executive Brief: strategy/executive-brief.md
      - Alliance Model: strategy/alliance-model.md
      - Platform vs. Agency: strategy/platform-vs-agency.md
  - Platform:
      - Nearshore IT Co-Pilot™: platform/nearshore-it-co-pilot.md
      - Axiom Cortex™: platform/axiom-cortex.md
      - Nebula Neural Search™: platform/nebula-neural-search.md
      - SSOT & Governance: platform/ssot-governance.md
      - Devices, MDM & EOR: platform/devices-mdm-eor.md
  - Process:
      - Overview: process/overview.md
      - Playbook Steps: process/playbook-steps.md
  - Performance:
      - BARS & KPIs: performance/bars-and-kpis.md
      - Quarterly Reviews: performance/quarterly-reviews.md
  - Security:
      - Security Basics: security/security-basics.md
      - Compliance & Privacy: security/compliance-and-privacy.md
  - ROI:
      - Metrics: roi/metrics.md
      - Estimator & Pricing: roi/estimator-links.md
  - RFP Toolkit:
      - Evaluation Checklist: rfp/evaluation-checklist.md
      - Scoring Rubric: rfp/scoring-rubric.md
  - Resources:
      - Featured Links for CTOs: resources/featured-links.md
      - TeamStation Website Sitemap: resources/site-sitemap.md
      - Publications: resources/publications.md
      - Book & Papers: resources/book-and-papers.md
      - Glossary: resources/glossary.md
      - LATAM Coverage: resources/coverage-latam.md
  - FAQ: faq/cto-faq.md
  - Schedule a Demo: https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ1JD2e4SmSzEC82NiTvzvUJNaghMafqlUdoTB9YlWfUSsJa2fC4uqoXGoOb9XNhRIsNa-IOIXSq