site_name: TeamStation AI
site_url: https://cto.teamstation.dev/
repo_name: TeamStation-AI/CTO-playbook
repo_url: https://github.com/TeamStation-AI/CTO-playbook
site_description: Build predictable, auditable nearshore engineering extensions with TeamStation AI™ under one SLA. Cognitive AI evaluations, onboarding, devices/MDM, EOR, and performance (BARS).

use_directory_urls: true

docs_dir: docs
strict: false

theme:
  name: material
  language: en
  favicon: "assets/TS new logo concept 2024.png"
  custom_dir: overrides
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - assets/custom.css
  - assets/custom.v2.css
  - assets/site.css

extra:
  links:
    demo: https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ1JD2e4SmSzEC82NiTvzvUJNaghMafqlUdoTB9YlWfUSsJa2fC4uqoXGoOb9XNhRIsNa-IOIXSq
    website: https://teamstation.dev/
    pricing: https://pricing.teamstation.dev/
    sitemap: https://teamstation.dev/sitemap.xml
    org: https://github.com/TeamStation-AI
    axiom_docs: https://docs.teamstation.dev/
    papers:
      redesigning-human-capacity: https://ssrn.com/abstract=5165433
      scientific-framework: https://ssrn.com/abstract=5188490
      nearshore-metrics: https://ssrn.com/abstract=5253470
    book: https://a.co/d/2B5zpDP
  social_image: https://teamstation.dev/og-image.png
  org:
    name: TeamStation AI
    url: https://teamstation.dev/
    image: https://teamstation.dev/og-image.png
    same_as:
      - https://github.com/TeamStation-AI

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.magiclink

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  - macros:
      include_dir: docs/snippets
  - htmlproofer:
      raise_error: false
      validate_external_urls: false
      ignore_urls:
        - "^mailto:"
        - "^tel:"
        - "^https://calendar.google.com/"
        - "^https://teamstation.dev/"
        - "^https://pricing.teamstation.dev/"
        - "^https://jobs.teamstation.dev/"
        - "^https://docs.teamstation.dev/"
        - "^https://ssrn.com/"
        - "^https://a.co/"

nav:
  - CTO Playbook: index.md
  - Strategy:
      - Executive Brief: strategy/executive-brief.md
      - Alliance Model: strategy/alliance-model.md
      - Platform vs. Agency: strategy/platform-vs-agency.md
  - Platform:
      - Nearshore IT Co-Pilot™: platform/nearshore-it-co-pilot.md
      - Axiom Cortex™: https://docs.teamstation.dev/
      - Nebula Neural Search™: platform/nebula-neural-search.md
      - SSOT & Governance: platform/ssot-governance.md
      - Devices, MDM & EOR: platform/devices-mdm-eor.md
  - Process:
      - Overview: process/overview.md
      - Playbook Steps: process/playbook-steps.md
  - Performance:
      - BARS & KPIs: performance/bars-and-kpis.md
      - Quarterly Reviews: performance/quarterly-reviews.md
  - Security:
      - Security Basics: security/security-basics.md
      - Compliance & Privacy: security/compliance-and-privacy.md
  - ROI:
      - Metrics: roi/metrics.md
      - Estimator & Pricing: roi/estimator-links.md
  - RFP Toolkit:
      - Evaluation Checklist: rfp/evaluation-checklist.md
      - Scoring Rubric: rfp/scoring-rubric.md
  - Resources:
      - Featured Links for CTOs: resources/featured-links.md
      - TeamStation Website Sitemap: resources/site-sitemap.md
      - Publications: resources/publications.md
      - Book & Papers: resources/book-and-papers.md
      - Glossary: resources/glossary.md
      - LATAM Coverage: resources/coverage-latam.md
  - FAQ: faq/cto-faq.md
  - Schedule a Demo: https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ1JD2e4SmSzEC82NiTvzvUJNaghMafqlUdoTB9YlWfUSsJa2fC4uqoXGoOb9XNhRIsNa-IOIXSq