title: TeamStation AI
description: CTO Playbook
url: https://cto.teamstation.dev
baseurl: ""

theme: null
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

permalink: pretty
search_enabled: true
color_scheme: dark

logo:
aux_links:
  "View on GitHub":
    - "https://github.com/TeamStation-AI/CTO-playbook"
